### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by GabeIggy** [flozz/rivalcfg#145]
```
$ rivalcfg -h
Traceback (most recent call last):
  File "/usr/local/bin/rivalcfg", line 33, in <module>
    sys.exit(load_entry_point('rivalcfg==4.1.0', 'console_scripts', 'rivalcfg')())
  File "/usr/local/lib/python3.6/dist-packages/rivalcfg-4.1.0-py3.6.egg/rivalcfg/__main__.py", line 45, in main
  File "/usr/local/lib/python3.6/dist-packages/rivalcfg-4.1.0-py3.6.egg/rivalcfg/__init__.py", line 29, in get_first_mouse
  File "/usr/local/lib/python3.6/dist-packages/rivalcfg-4.1.0-py3.6.egg/rivalcfg/mouse.py", line 30, in get_mouse
  File "/usr/local/lib/python3.6/dist-packages/rivalcfg-4.1.0-py3.6.egg/rivalcfg/usbhid.py", line 93, in open_device
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
```

**Comment by GabeIggy** [comment]
Please mark it as invalid. Reinstalling fixed the problem.

**Comment by flozz** [comment]
Ok, cool if it worked :)
