### ISSUE TITLE
Software does not work at all on Debian with RIval 300

### ISSUE THREAD

**Issue by Draluy** [flozz/rivalcfg#25]
Hello,

I am using Debian testing, and installed the software from sources with apparently no problem. 
But all the commands I use have no effect on the mouse, for example rivalcfg -c 00f, or  rivalcfg -e steady.

I don't know how to give you more info on this, or what steps I could take to try and pinpoint the issue.
Please let me know.

**Comment by Draluy** [comment]
Hi again, 

I just saw similar issues and figured out that I could start an windows vm and capture packets with wireshark. Unfortunately my plate is full at the moment, hopefully someone can lend you a Rival 300. If by any chance you're in bordeaux, I'd be happy to do so.

**Comment by flozz** [comment]
Hello,

Can you provide the result of the following commands:
```
rivalcfg -l
```
```
lsusb
```
```
dmesg | grep -C 5 hidraw
```

Best regards,

**Comment by flozz** [comment]
Sory, I am not in Bordeau but in Lyon :)

**Comment by Draluy** [comment]
Here you go:

```
$ rivalcfg -l                                                                                                          
SteelSeries Rival                             1038:1384                                                                                                                                                       
SteelSeries Rival 100                         1038:1702                                                                                                                                                       
SteelSeries Rival 300                         1038:1710   (plugged)                                                                                                                                           
SteelSeries Rival 300 CS:GO Fade Edition      1038:1394    
```        

```                                                                                                                                                   
$ lsusb                                                                                                                
Bus 002 Device 007: ID 19d2:1350 ZTE WCDMA Technologies MSM                                                                                                                                                   
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub                                                                                                                                     
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub                                                                                                                                                
Bus 001 Device 006: ID 1038:1710 SteelSeries ApS                                                                                                                                                                                            
Bus 001 Device 003: ID 04b4:0101 Cypress Semiconductor Corp. Keyboard/Hub                                                                                                                                                                   
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub                                                                                                                                                                   
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub                                                                                                                                                                              
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub                                                                                                                                                                              
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub                                                                                                                                                            ```        
```             
```                                        
$ sudo dmesg | grep -C 5 hidraw                                                                                                                      
[sudo] password for redeyed:                                                                                                                                                                                                                
[    1.892170] usb 1-1.1: new low-speed USB device number 3 using ehci-pci                                                                                                                                                                  
[    2.007255] usb 1-1.1: New USB device found, idVendor=04b4, idProduct=0101                                                                                                                                                               
[    2.007258] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0                                                                                                                                                          
[    2.007260] usb 1-1.1: Product: SteelS쀁̄Љ̒DATA
[    2.007261] usb 1-1.1: Manufacturer: DATACOMP
[    2.036900] hidraw: raw HID events driver (C) Jiri Kosina
[    2.046395] usbcore: registered new interface driver usbhid
[    2.046396] usbhid: USB HID core driver
[    2.047574] input: DATACOMP SteelS쀁̄Љ̒DATA as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.1/1-1.1:1.0/0003:04B4:0101.0001/input/input5
[    2.088231] [drm] ib test on ring 5 succeeded
[    2.104419] hid-generic 0003:04B4:0101.0001: input,hidraw0: USB HID v1.00 Keyboard [DATACOMP SteelS쀁̄Љ̒DATA] on usb-0000:00:1a.0-1.1/input0
[    2.104580] input: DATACOMP SteelS쀁̄Љ̒DATA as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.1/1-1.1:1.1/0003:04B4:0101.0002/input/input6
[    2.112191] usb 1-1.2: new full-speed USB device number 4 using ehci-pci
[    2.164308] hid-generic 0003:04B4:0101.0002: input,hidraw1: USB HID v1.00 Device [DATACOMP SteelS쀁̄Љ̒DATA] on usb-0000:00:1a.0-1.1/input1
[    2.224426] usb 1-1.2: New USB device found, idVendor=1038, idProduct=1360
[    2.224429] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=2
[    2.224431] usb 1-1.2: Product: SteelSeries Gaming Device
[    2.224432] usb 1-1.2: Manufacturer: Ruling Technologies Sdn. Bhd.
[    2.224433] usb 1-1.2: SerialNumber: SteelSeries Gaming Device
--
[    3.197570] fbcon: radeondrmfb (fb0) is primary device
[    3.242633] Console: switching to colour frame buffer device 210x65
[    3.246733] radeon 0000:01:00.0: fb0: radeondrmfb frame buffer device
[    3.260272] [drm] Initialized radeon 2.48.0 20080528 for 0000:01:00.0 on minor 0
[    7.405074] input: Ruling Technologies Sdn. Bhd. SteelSeries Gaming Device as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.0/0003:1038:1360.0003/input/input7
[    7.405305] hid-generic 0003:1038:1360.0003: input,hidraw2: USB HID v1.00 Mouse [Ruling Technologies Sdn. Bhd. SteelSeries Gaming Device] on usb-0000:00:1a.0-1.2/input0
[   12.525152] input: Ruling Technologies Sdn. Bhd. SteelSeries Gaming Device as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.1/0003:1038:1360.0004/input/input8
[   12.584871] hid-generic 0003:1038:1360.0004: input,hidraw3: USB HID v1.00 Keyboard [Ruling Technologies Sdn. Bhd. SteelSeries Gaming Device] on usb-0000:00:1a.0-1.2/input1
[   17.648176] hid-generic 0003:1038:1360.0005: hiddev0,hidraw4: USB HID v1.00 Device [Ruling Technologies Sdn. Bhd. SteelSeries Gaming Device] on usb-0000:00:1a.0-1.2/input2
[   17.668285] PM: Starting manual resume from disk
[   17.668289] PM: Hibernation image partition 8:6 present
[   17.668290] PM: Looking for hibernation image.
[   17.668451] PM: Image not found (code -22)
[   17.668452] PM: Hibernation image not present or could not be loaded.
--
[31484.494385] usb 1-1.2: new full-speed USB device number 5 using ehci-pci
[31484.603755] usb 1-1.2: New USB device found, idVendor=1038, idProduct=1710
[31484.603757] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[31484.603759] usb 1-1.2: Product: SteelSeries Rival 300 Gaming Mouse
[31484.603761] usb 1-1.2: Manufacturer: SteelSeries
[31484.605796] hid-generic 0003:1038:1710.0006: hiddev0,hidraw2: USB HID v1.11 Device [SteelSeries SteelSeries Rival 300 Gaming Mouse] on usb-0000:00:1a.0-1.2/input0
[31484.606817] input: SteelSeries SteelSeries Rival 300 Gaming Mouse as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.1/0003:1038:1710.0007/input/input38
[31484.607160] hid-generic 0003:1038:1710.0007: input,hidraw3: USB HID v1.11 Mouse [SteelSeries SteelSeries Rival 300 Gaming Mouse] on usb-0000:00:1a.0-1.2/input1
[31484.609038] input: SteelSeries SteelSeries Rival 300 Gaming Mouse as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.2/0003:1038:1710.0008/input/input39
[31484.666690] hid-generic 0003:1038:1710.0008: input,hidraw4: USB HID v1.11 Keyboard [SteelSeries SteelSeries Rival 300 Gaming Mouse] on usb-0000:00:1a.0-1.2/input2
[33210.563632] usb 1-1.2: USB disconnect, device number 5
[33213.858014] usb 1-1.2: new full-speed USB device number 6 using ehci-pci
[33213.967422] usb 1-1.2: New USB device found, idVendor=1038, idProduct=1710
[33213.967424] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[33213.967426] usb 1-1.2: Product: SteelSeries Rival 300 Gaming Mouse
[33213.967427] usb 1-1.2: Manufacturer: SteelSeries
[33213.969467] hid-generic 0003:1038:1710.0009: hiddev0,hidraw2: USB HID v1.11 Device [SteelSeries SteelSeries Rival 300 Gaming Mouse] on usb-0000:00:1a.0-1.2/input0
[33213.970529] input: SteelSeries SteelSeries Rival 300 Gaming Mouse as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.1/0003:1038:1710.000A/input/input40
[33213.971355] hid-generic 0003:1038:1710.000A: input,hidraw3: USB HID v1.11 Mouse [SteelSeries SteelSeries Rival 300 Gaming Mouse] on usb-0000:00:1a.0-1.2/input1
[33213.973302] input: SteelSeries SteelSeries Rival 300 Gaming Mouse as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.2/0003:1038:1710.000B/input/input41
[33214.030295] hid-generic 0003:1038:1710.000B: input,hidraw4: USB HID v1.11 Keyboard [SteelSeries SteelSeries Rival 300 Gaming Mouse] on usb-0000:00:1a.0-1.2/input2
```

**Comment by flozz** [comment]
According to the informations you provided, it should work... can you try to send commands manually to the mouse?

    echo -en "\x08\x01\xFF\x00\x00" > /dev/hidraw2"

This should changes the mouse logo to `red`

**Comment by Draluy** [comment]
It doesn't, unfortunately :(

**Comment by Draluy** [comment]
I was wondering if you still have that virtual machine image with windows, the steelseries program and wireshark installed? If so, would you mind uploading it somewhere so I can try to dump the packets myself? It would save me some of trouble trying to find a copy of windows.

**Comment by flozz** [comment]
I used the Windows VM only to play with the SteelSeries Engine 3, the capture was made from Wireshark on Linux (but it should be possible to do it from the Windows itself).

Anyway, it is easy to find Windows VM image for Virtualbox, as Microsoft provide them as a part of its "Modern IE" program. You will find everything you need there:

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

:)

**Comment by Draluy** [comment]
Oh cool, thx.

**Comment by Draluy** [comment]
Hello.

I mounted a windows vm and basivally followed your tutorial, that is very well done btw, and changed the color of the display.
Here is the data when changing color to #112233
08:01:11:22:33:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00

**Comment by Draluy** [comment]
I think I have a frame like this before:

```
URB setup
    bmRequestType: 0x21
    bRequest: 9
    wValue: 0x0200
    wIndex: 0 (0x0000)
    wLength: 32
    Data Fragment: 0802ff180000000000000000000000000000000000000000...
```

Then the frame that changes the color:
```
URB setup
    bmRequestType: 0x21
    bRequest: 9
    wValue: 0x0200
    wIndex: 0 (0x0000)
    wLength: 32
    Data Fragment: 080101122300000000000000000000000000000000000000...
```
Then another frame:
```
URB setup
    bmRequestType: 0x21
    bRequest: 9
    wValue: 0x0200
    wIndex: 0 (0x0000)
    wLength: 32
    Data Fragment: 040001000000000000000000000000000000000000000000...
```

Does this sound different from what you have with your mouse?

**Comment by flozz** [comment]
Ok, so it seems to be the same command set as the one I have, you can find it here:

* https://github.com/flozz/rivalcfg/blob/master/doc/rival300-spec.md

---

So the issue should be in detecting the right interface where the commands are sent.

Can you try to exec the following command:

    dmesg | grep 1038:1710

This will give you lines like this:

> [33213.969467] hid-generic 0003:1038:1710.0009: hiddev0,**hidraw2**: USB HID v1.11 Device [SteelSeries SteelSeries Rival 300 Gaming Mouse] on usb-0000:00:1a.0-1.2/input0

then try to write commands to each hidraw interfaces listed (hidrawXXX → /dev/hidrawXXX)

    echo -en "\x08\x01\xFF\x00\x00" > /dev/hidrawXXX"

(by looking at the logs you provided before, the interfaces should be `/dev/hidraw2`, `/dev/hidraw3`, and `/dev/hidraw4`, but this depends on what is plugged on the PC (other mouse, keyboard, gamepad,...))

If nothing work, you can try `/dev/hidraw0` too

**Comment by Draluy** [comment]
Right now its hidraw3:

```
[ 2530.339469] hid-generic 0003:1038:1710.0014: input,hidraw3: USB HID v1.11 Mouse [SteelSeries SteelSeries Rival 300 Gaming Mouse] on usb-0000:00:1a.0-1.2/input1
```

But still no luck. I can't write to hidraw0, permission is denied, even with sudo.

**Comment by flozz** [comment]
If you done

    sudo echo ... > /dev/hidrawX

it cannot work, because only the `echo` command is executed with the super user rights, the file redirection (`>`) is still done with you normal user right :)

You have to open a root shell to make it work. for example:

    sudo bash
    echo -en "\x08\x01\xFF\x00\x00" > /dev/hidraw3

:)

**Comment by Draluy** [comment]
Nice suggestion, did not now that. Alas, still not working.

Tried to change it blue with this for eg.:
```
root@reds-pc:/home/redeyed/rivalcfg# echo -en "\x08\x01\x00\x00\xFF" > /dev/hidraw3
```

**Comment by flozz** [comment]
I will try to make a script tomorrow to make some tests, that is strange that it not works on any of the 3 hidraw interfaces provided by the mouse :(

**Comment by flozz** [comment]
Hello,

Can you run this script and tell me what is the output (you will have to install pyusb first, this can be done with the `pip install pyusb` command):

```python
#!/usr/bin/env python

import usb.core
import usb.util

dev = usb.core.find(idVendor=0x1038, idProduct=0x1710)
print(dev)
```

**Comment by Draluy** [comment]
Here you go:

```
DEVICE ID 1038:1710 on Bus 001 Address 004 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :  0x110 USB 1.1
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :   0x40 (64 bytes)
 idVendor               : 0x1038
 idProduct              : 0x1710
 bcdDevice              :   0x68 Device 0.68
 iManufacturer          :    0x1 Error Accessing String
 iProduct               :    0x2 Error Accessing String
 iSerialNumber          :    0x0 
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 200 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x54 (84 bytes)
   bNumInterfaces       :    0x3
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xa0 Bus Powered, Remote Wakeup
   bMaxPower            :   0x64 (200 mA)
    INTERFACE 0: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x81: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x20 (32 bytes)
       bInterval        :    0x1
    INTERFACE 1: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x1
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x1
     bInterfaceProtocol :    0x2
     iInterface         :    0x0 
      ENDPOINT 0x82: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x82 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :    0x8 (8 bytes)
       bInterval        :    0x1
    INTERFACE 2: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x2
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x83: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x83 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :    0x9 (9 bytes)
       bInterval        :    0x1

```

**Comment by flozz** [comment]
Thank you, I will compare this tomorrow with the output of my own mouse (I don't have it right now, I let it at work...) :)

**Comment by flozz** [comment]
Hello,

I made some research, can you try this:

    pip install hidapi

```python
import hid

for device_info in hid.enumerate():
    if not (device_info["vendor_id"] == 0x1038 and device_info["product_id"] == 0x1710 and device_info["interface_number"] == 0):
        continue

    device = hid.device()
    device.open_path(device_info["path"])
    device.write([0x08, 0x01, 0x00, 0xFF, 0xFF])
    device.close()
```

this should set the logo color to cyan

**Comment by Draluy** [comment]
Hi, 

Here's the python script I use, just in case:

```
#!/usr/bin/env python

import hid

for device_info in hid.enumerate():
    if not (device_info["vendor_id"] == 0x1038 and device_info["product_id"] == 0x1710 and device_info["interface_number"] == 0):
        continue

    device = hid.device()
    print device_info
    device.open_path(device_info["path"])
    device.write([0x08, 0x01, 0x00, 0xFF, 0xFF])
    device.close()
```
I added "print device_info" to check the value, that line prints out:

```
{'usage_page': 0, 'product_id': 5904, 'interface_number': 0, 'manufacturer_string': '', 'vendor_id': 4152, 'release_number': 104, 'serial_number': '', 'usage': 0, 'path': '0001:0004:00', 'product_string': ''}
```

Then the line "device.open_path(device_info["path"])" fails with the message:

```
Traceback (most recent call last):
  File "./test2.py", line 11, in <module>
    device.open_path(device_info["path"])
  File "hid.pyx", line 72, in hid.device.open_path (hid.c:1909)
IOError: open failed
```

**Comment by Draluy** [comment]
I also tried with interface number 1 and 2 just in case, but same problem.

**Comment by Draluy** [comment]
Ok, so I installed hidapi as root, using "pip install hidapi"

I tried the script 3 times, each time for a different interface number, here are the outputs:
```
root@reds-pc:/home/redeyed/rivalcfg# ./test2.py 
{'usage_page': 0, 'product_id': 5904, 'interface_number': 2, 'manufacturer_string': u'SteelSeries', 'vendor_id': 4152, 'release_number': 104, 'serial_number': '', 'usage': 0, 'path': '0001:0004:02', 'product_string': u'SteelSeries Rival 300 Gaming Mouse'}
root@reds-pc:/home/redeyed/rivalcfg# ./test2.py 
{'usage_page': 0, 'product_id': 5904, 'interface_number': 0, 'manufacturer_string': u'SteelSeries', 'vendor_id': 4152, 'release_number': 104, 'serial_number': '', 'usage': 0, 'path': '0001:0004:00', 'product_string': u'SteelSeries Rival 300 Gaming Mouse'}
root@reds-pc:/home/redeyed/rivalcfg# ./test2.py 
{'usage_page': 0, 'product_id': 5904, 'interface_number': 1, 'manufacturer_string': u'SteelSeries', 'vendor_id': 4152, 'release_number': 104, 'serial_number': '', 'usage': 0, 'path': '0001:0004:01', 'product_string': u'SteelSeries Rival 300 Gaming Mouse'}
```
As you can see, no more errorsm, but the color doesnt change
Note:  after the third time, with interface 1,  I could not move the mouse at all anymore, I had to unplug/replug it. 

I tried a fourth time with interface number 0 just in case, but no color change.

**Comment by flozz** [comment]
Hello,

I wonder if this issue is related to #5. I see two possibilities to this issue:

1. It is a problem specific to Debian (but as Ubuntu is very close to Debian,
   if it works with Ubuntu, it should work on Debian too).

2. The device receive the commands but ignores them. Maybe the SteelSeries
   Engine 3 send some commande at startup to init / unlock the device? Can you
   try to capture on the USB Bus before connecting to the mouse to the VM and
   then, plug the mouse to the VM and start the SteelSeries Engine 3. Does it
   send some extra command to the mouse at startup (one that is not listed
   [here][rival300])?

[rival300]: https://github.com/flozz/rivalcfg/blob/master/doc/rival300-spec.md


> Note: after the third time, with interface 1, I could not move the mouse at
> all anymore, I had to unplug/replug it.

This is normal: the interface No 1 is the one that is used to send mouse
coordinate to the PC... And the hidapi lib detach the kernel driver from the
interface to be able to communicate...

**Comment by Draluy** [comment]
Ok. I'm a bit busy tonight and tomorrow, I'll try to do this this week-end, I'll keep you posted.
Thanks for your involvement so far.

**Comment by flozz** [comment]
OK, thank you very much for your help :)

**Comment by flozz** [comment]
I have some (good) news, 

Thanks to the mouse @Thiblizz [send me](https://github.com/flozz/rivalcfg/issues/28#issuecomment-301319404), I was able to find what is going on:

![SS Engine vs Rivalcfg](https://cloud.githubusercontent.com/assets/971438/26170448/c3f3a2ea-3b41-11e7-902a-5a8f678a2757.png)

on the left: a capture of a frame sent by the SS Engine, on the right: a frame sent by rivalcfg. There is **one** major difference: the `wValue` field.

* With the SS Engine, this field is always `0x0200`
* With rivalcfg, the value depends on what is sent in the data (eg `08 01 FF 00 00` → `0x0208`)

I do not know what this field means and what to do to change its value... **BUT**, I found that starting the data with `0x00` changes the value of this field to the right one (`0x0200`) AND, that this initial zero is not sent in with the data... I will have to read some USB spec to find out why...

![start data with zero](https://cloud.githubusercontent.com/assets/971438/26170684/93d4091e-3b42-11e7-9b2c-0e0f0d0cdbe7.png)

Anyway, it worked. I was able to change the color of the mouse etc. :D 

**→ I will release a fix soon to make Rival 300 work again !!**

And I whant to thank you again for your involvement in this project :)

**Comment by WinteryFox** [comment]
That's great hope you can release the fix soon so I won't be stuck on 800dpi anymore!

**Comment by nicob89** [comment]
Wow! Amazing job. I'm anxious for the release. I hope I can learn some stuff from this too!

**Comment by flozz** [comment]
I just released **rivalcfg 2.5.2** and it should work now. Please let me know if it works for you too! :)

**Comment by WinteryFox** [comment]
I have tested it now and everything seems to work just fine now! Thanks a lot for the update!

**Comment by Draluy** [comment]
Great news! We almost had it pinned down!
I just tested it and can confirm it works. Thanks so much for your selfless efforts, now I can pimp my mouse! \o/

**Comment by pijusme** [comment]
hello i dont understand anything from what your writing cuz its programing but i have the issue of rival 300 that doesnt work at all after the firmware update when i press the dpi left and right mouse buttons in works but i cant change dpi or anything on it the mouse wheels or any other buttons than the left and right button of mouse doesnt work i would like to fix it but i dont understand the programming would like you to help me

**Comment by flozz** [comment]
Hello,

Is your problem related to rivalcfg? If yes, please open a new issue with the following information:

* OS, OS Version / Linux distro
* rivalcfg version (`rivalcfg --version`)
* python version (`python --version`)

If your problem related only to a problem with your Rival 300 mouse, you are posting at the wrong place. This project is a small command line tool that provides support of some SteelSeries Rival mice for those who cannot (or do not want to) use the SteelSeries Engine 3 (mostly people on Linux). If you need support with your mouse, you can post at the following places:

* SteelSeries subreddit: https://www.reddit.com/r/steelseries/
* Gaming on StackExchange: https://gaming.stackexchange.com/
* SteelSeries Support: https://steelseries.com/login?next=/dashboard/support

:)
