### ISSUE TITLE
IOError: [Errno 13] Permission denied: u'/dev/hidraw2' [Rival 100]

### ISSUE THREAD

**Issue by gccltl** [flozz/rivalcfg#27]
I have this error:

```
Traceback (most recent call last):
  File "/home/matas/.local/bin/rivalcfg", line 9, in <module>
    load_entry_point('rivalcfg==2.5.1', 'console_scripts', 'rivalcfg')()
  File "/home/matas/.local/lib/python2.7/site-packages/rivalcfg/cli.py", line 172, in main
    mouse = RivalMouse(profile)
  File "/home/matas/.local/lib/python2.7/site-packages/rivalcfg/rival_mouse.py", line 24, in __init__
    self._device_open()
  File "/home/matas/.local/lib/python2.7/site-packages/rivalcfg/rival_mouse.py", line 48, in _device_open
    self._device = open(self.device_path, "wb")
IOError: [Errno 13] Permission denied: u'/dev/hidraw2'
matas@matas-H81M-D2V:~$ 

```
Ubuntu 16.04, Rival 100

**Comment by flozz** [comment]
hello,

It seems that the udev rules have not been installed. Execute the following commands, it should fix your problem:

```
sudo wget https://raw.githubusercontent.com/flozz/rivalcfg/master/rivalcfg/data/99-steelseries-rival.rules -O /etc/udev/rules.d/99-steelseries-rival.rules
```

```
sudo udevadm trigger
```

then it should work :)

**Comment by gccltl** [comment]
Everything works! Thank you
