### ISSUE TITLE
Python3: TypeError: object of type 'map' has no len()

### ISSUE THREAD

**Issue by sdfgeoff** [flozz/rivalcfg#61]
Full log:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/Data/src/rivalcfg/rivalcfg/__main__.py", line 99, in <module>
    main(sys.argv[1:])
  File "/mnt/Data/src/rivalcfg/rivalcfg/__main__.py", line 92, in main
    getattr(mouse, option)(*value)
  File "/mnt/Data/src/rivalcfg/rivalcfg/mouse.py", line 87, in _exec_command
    bytes_ = getattr(command_handlers, handler)(command, *args)
  File "/mnt/Data/src/rivalcfg/rivalcfg/command_handlers.py", line 110, in rgbuniversal_handler
    header[rgb_format["repeat"]] = 1 if len(colors) == 1 or triggers > 0 else 0
TypeError: object of type 'map' has no len()
```

A trivial fix is to change (on line 95):
`colors = map(helpers.color_string_to_rgb, colors)`
into:
`colors = list(map(helpers.color_string_to_rgb, colors))`

**Comment by flozz** [comment]
Hi,

Can you PR this change on the project ? :)

**Comment by sdfgeoff** [comment]
Uh yup, good point. I should have thought of that. 
Submitted #63

**Comment by flozz** [comment]
Thank you, I will release both the fix and the rival600 support this week (probably this weekend) :)
