### ISSUE TITLE
TypeError, fails to run

### ISSUE THREAD

**Issue by defkeh** [flozz/rivalcfg#7]
Attempting to run fails with TypeError 
    
    $ DEBUG_DRY=true rivalcfg -c red
    [DEBUG] Debugging rivalcfg 2.4.1...
    [DEBUG] Dry run enabled
    [DEBUG] Mouse profile found: SteelSeries Rival 300
    Traceback (most recent call last):
    File "/usr/bin/rivalcfg", line 9, in <module>
        load_entry_point('rivalcfg==2.4.1', 'console_scripts', 'rivalcfg')()
    File "/usr/lib/python3.5/site-packages/rivalcfg/cli.py", line 143, in main
        _generate_mouse_cli_options(parser, profile)
    File "/usr/lib/python3.5/site-packages/rivalcfg/cli.py", line 71, in _generate_mouse_cli_options
        choices_to_string(cmd["choices"]),
    File "/usr/lib/python3.5/site-packages/rivalcfg/helpers.py", line 129, in choices_to_string
        return ", ".join(choices_to_list(choices))
    File "/usr/lib/python3.5/site-packages/rivalcfg/helpers.py", line 120, in choices_to_list
        return map(str, sorted(choices.keys()))
    TypeError: unorderable types: str() < int()

**Comment by flozz** [comment]
OK, I can reproduce with Python 3.5 (it work fine with Python 2.7). I will fix it soon, thanks :)

**Comment by flozz** [comment]
Fixed in rivalcfg 2.4.2! :)
